version: '2'
services:
  app:
    image: miguelpeixe/electoral-canvas:latest
    build: .
    command: npm start
    links:
    - redis
    ports:
    - 8000:8000
    environment:
      REDIS: "redis://redis:6379"
  redis:
    image: redis
    volumes:
    - ./.data/redis:/data
